/*---------------------------------------------------------------------------*\
 #####  #     # |
 #      # # # # | Project Name: EPFL
 #####  #  #  # | Source Code URL:
     #  #     # | Copyright (C) 2025
 #####  #     # |
-------------------------------------------------------------------------------
License
    This file is part of @ProjectName.
    @ProjectName is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    @ProjectName is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.
    You should have received a copy of the GNU General Public License
    along with @ProjectName. If not, see <http://www.gnu.org/licenses/>.
coding rules:
    Max nb. of lines: 80
    case: Camel Case (other cases: )
    attributes: end with a underscore (eg: attributeName_)
header file:
    Header file contains class definitions and function
    declarations (prototypes).
Class
    @namespace::cercle
Description
    description of the class.
implementation file:
    tourDeMagie.C
\*---------------------------------------------------------------------------*/
#ifndef TOURDEMAGIE_H  // include guard
#define TOURDEMAGIE_H

#include <iostream>
#include <vector>
#include <cmath>

class magicien{



};//end-of-class-magicien


class assistant{

}; //end-of-class-assistant

class spectateur{
    private:
        int age=0;
        int montantDansPoche=0.0

    public:
        
    //Constructeur
        spectateur();

}; //end-of-class-spectateur

class papier{

}; //end-of-class-papier

#endif
